// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _move_request{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u32 * k1, const u32 * k2);
  const size_t sizes[2];

  u32 * entity;
  vec3 * move;
  icy_mem * entity_area;
  icy_mem * move_area;
}move_request;

move_request * move_request_create(const char * optional_name);
void move_request_set(move_request * table, u32 entity, vec3 move);
void move_request_insert(move_request * table, u32 * entity, vec3 * move, size_t count);
void move_request_lookup(move_request * table, u32 * keys, size_t * out_indexes, size_t count);
void move_request_remove(move_request * table, u32 * keys, size_t key_count);
void move_request_clear(move_request * table);
void move_request_unset(move_request * table, u32 key);
bool move_request_try_get(move_request * table, u32 * entity, vec3 * move);
void move_request_print(move_request * table);
size_t move_request_iter(move_request * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
