// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


move_request * move_request_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"entity", (char *)"move"};
  static const char * const column_types[] = {"u32", "vec3"};
  move_request * instance = calloc(sizeof(move_request), 1);
  icy_table_init((icy_table * )instance, optional_name, 2, (unsigned int[]){sizeof(u32), sizeof(vec3)}, (char *[]){(char *)"entity", (char *)"move"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void move_request_insert(move_request * table, u32 * entity, vec3 * move, size_t count){
  void * array[] = {(void* )entity, (void* )move};
  icy_table_inserts((icy_table *) table, array, count);
}

void move_request_set(move_request * table, u32 entity, vec3 move){
  void * array[] = {(void* )&entity, (void* )&move};
  icy_table_inserts((icy_table *) table, array, 1);
}

void move_request_lookup(move_request * table, u32 * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void move_request_remove(move_request * table, u32 * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void move_request_clear(move_request * table){
  icy_table_clear((icy_table *) table);
}

void move_request_unset(move_request * table, u32 key){
  move_request_remove(table, &key, 1);
}

bool move_request_try_get(move_request * table, u32 * entity, vec3 * move){
  void * array[] = {(void* )entity, (void* )move};
  void * column_pointers[] = {(void *)table->entity, (void *)table->move};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(u32), sizeof(vec3)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void move_request_print(move_request * table){
  icy_table_print((icy_table *) table);
}

size_t move_request_iter(move_request * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
