// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _palette{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[1];
  
  u32 * color;
  icy_mem * color_area;
}palette;

// a vector index.
typedef struct{
  size_t index;
}palette_index;

typedef struct{
  size_t index;
  size_t count;
}palette_indexes;

palette * palette_create(const char * optional_name);
palette_index palette_alloc(palette * table);
palette_indexes palette_alloc_sequence(palette * table, size_t count);
void palette_remove(palette * table, palette_index index);
void palette_remove_sequence(palette * table, palette_indexes * indexes);
void palette_clear(palette * table);
void palette_optimize(palette * table);
void palette_destroy(palette ** table);
