// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

pstring * pstring_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key"};
  static const char * const column_types[] = {"u32"};

  pstring * instance = calloc(sizeof(pstring), 1);
  unsigned int sizes[] = {sizeof(u32)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 1;
  for(unsigned int i = 0; i < 1; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


pstring_index pstring_alloc(pstring * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  pstring_index index;
  index.index = idx.index;
  return index;
}

pstring_indexes pstring_alloc_sequence(pstring * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  pstring_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void pstring_remove(pstring * table, pstring_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void pstring_remove_sequence(pstring * table, pstring_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void pstring_clear(pstring * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void pstring_optimize(pstring * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void pstring_destroy(pstring ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
