// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

subtexdef * subtexdef_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"x", (char *)"y", (char *)"w", (char *)"h", (char *)"texture"};
  static const char * const column_types[] = {"f32", "f32", "f32", "f32", "texdef_index"};

  subtexdef * instance = calloc(sizeof(subtexdef), 1);
  unsigned int sizes[] = {sizeof(f32), sizeof(f32), sizeof(f32), sizeof(f32), sizeof(texdef_index)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 5;
  for(unsigned int i = 0; i < 5; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


subtexdef_index subtexdef_alloc(subtexdef * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  subtexdef_index index;
  index.index = idx.index;
  return index;
}

subtexdef_indexes subtexdef_alloc_sequence(subtexdef * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  subtexdef_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void subtexdef_remove(subtexdef * table, subtexdef_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void subtexdef_remove_sequence(subtexdef * table, subtexdef_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void subtexdef_clear(subtexdef * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void subtexdef_optimize(subtexdef * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void subtexdef_destroy(subtexdef ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
