// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

texdef * texdef_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"width", (char *)"height", (char *)"path", (char *)"texture"};
  static const char * const column_types[] = {"u32", "u32", "pstring_indexes", "u32"};

  texdef * instance = calloc(sizeof(texdef), 1);
  unsigned int sizes[] = {sizeof(u32), sizeof(u32), sizeof(pstring_indexes), sizeof(u32)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 4;
  for(unsigned int i = 0; i < 4; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


texdef_index texdef_alloc(texdef * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  texdef_index index;
  index.index = idx.index;
  return index;
}

texdef_indexes texdef_alloc_sequence(texdef * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  texdef_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void texdef_remove(texdef * table, texdef_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void texdef_remove_sequence(texdef * table, texdef_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void texdef_clear(texdef * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void texdef_optimize(texdef * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void texdef_destroy(texdef ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
