// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _texdef{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[4];
  
  u32 * width;
  u32 * height;
  pstring_indexes * path;
  u32 * texture;
  icy_mem * width_area;
  icy_mem * height_area;
  icy_mem * path_area;
  icy_mem * texture_area;
}texdef;

// a vector index.
typedef struct{
  size_t index;
}texdef_index;

typedef struct{
  size_t index;
  size_t count;
}texdef_indexes;

texdef * texdef_create(const char * optional_name);
texdef_index texdef_alloc(texdef * table);
texdef_indexes texdef_alloc_sequence(texdef * table, size_t count);
void texdef_remove(texdef * table, texdef_index index);
void texdef_remove_sequence(texdef * table, texdef_indexes * indexes);
void texdef_clear(texdef * table);
void texdef_optimize(texdef * table);
void texdef_destroy(texdef ** table);
