// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

tile_material * tile_material_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"type", (char *)"material_id"};
  static const char * const column_types[] = {"material_type", "u32"};

  tile_material * instance = calloc(sizeof(tile_material), 1);
  unsigned int sizes[] = {sizeof(material_type), sizeof(u32)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 2;
  for(unsigned int i = 0; i < 2; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


tile_material_index tile_material_alloc(tile_material * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  tile_material_index index;
  index.index = idx.index;
  return index;
}

tile_material_indexes tile_material_alloc_sequence(tile_material * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  tile_material_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void tile_material_remove(tile_material * table, tile_material_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void tile_material_remove_sequence(tile_material * table, tile_material_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void tile_material_clear(tile_material * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void tile_material_optimize(tile_material * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void tile_material_destroy(tile_material ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
