// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _tile_material{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[2];
  
  material_type * type;
  u32 * material_id;
  icy_mem * type_area;
  icy_mem * material_id_area;
}tile_material;

// a vector index.
typedef struct{
  size_t index;
}tile_material_index;

typedef struct{
  size_t index;
  size_t count;
}tile_material_indexes;

tile_material * tile_material_create(const char * optional_name);
tile_material_index tile_material_alloc(tile_material * table);
tile_material_indexes tile_material_alloc_sequence(tile_material * table, size_t count);
void tile_material_remove(tile_material * table, tile_material_index index);
void tile_material_remove_sequence(tile_material * table, tile_material_indexes * indexes);
void tile_material_clear(tile_material * table);
void tile_material_optimize(tile_material * table);
void tile_material_destroy(tile_material ** table);
